install:
	cp plotcsv.py ~/bin/plotcsv
	chmod u+x ~/bin/plotcsv

	cp openchrome.sh ~/bin/openchrome
	chmod u+x ~/bin/openchrome
	cp opensafari.sh ~/bin/opensafari
	chmod u+x ~/bin/opensafari

	rm -f ~/bin/now
	ln -s ~/Note/script/now.py ~/bin/now
	rm -f ~/bin/notefind
	ln -s ~/Note/script/notefind.py ~/bin/notefind


